export const siteConfig = {
  supportEmail: "contact@ericstrohmaier.com",
  name: "Eric Strohmaier",
  domain: "ericstrohmaier.com",
  url: "https://ericstrohmaier.com",
  description:
    "I build personal software. Full-stack developer shipping SaaS products, AI tools, Chrome extensions, and automations. Fast shipping. Long partnerships.",
  keywords: [
    "Eric Strohmaier",
    "Full-Stack Developer",
    "Software Developer",
    "Freelance Developer",
    "AI Tools",
    "SaaS Developer",
    "React",
    "Next.js",
    "TypeScript",
    "Chrome Extensions",
    "LLMs",
    "Automations",
    "Openclaw setup",
    "OpenCLAW",
    "AI consulting",
    "AI development",
  ],
  ogImage: "https://ericstrohmaier.com/og-image.jpeg",
  links: {
    twitter: "https://twitter.com/EricStrohmaier",
    github: "https://github.com/EricStrohmaier",
    linkedin: "https://www.linkedin.com/in/eric-strohmaier-3a0767267/",
    email: "mailto:contact@ericstrohmaier.com",
  },
}
