import {
  Home,
  Building2,
  Users,
  Clock,
  Zap,
  Repeat,
  CalendarCheck,
  ShieldCheck,
  Lock,
  Database,
  PhoneCall,
  Rocket,
  Gauge,
  TrendingUp,
  FileText,
  Hammer,
  Star,
  Quote,
  Check,
  Wrench,
  MessageSquare,
  Search,
  Mail,
  BarChart3,
  Settings,
  Sparkles,
  Calculator,
  Scale,
  Receipt,
  FolderKanban,
  Bot,
  Workflow,
  MapPin,
  Phone,
  Globe,
  Camera,
  Megaphone,
  ClipboardList,
  FileSpreadsheet,
  Banknote,
  Shield,
  Smartphone,
  Send,
  Bell,
  LineChart,
  Layers,
  Plug,
  Table2,
  FileCheck,
  Folder,
  Inbox,
  Timer,
  type LucideIcon,
} from "lucide-react"

/**
 * String-keyed icon registry so vertical *content* (lib/verticals/*) stays
 * plain serializable data and only the renderer touches React components.
 */
export const ICONS = {
  home: Home,
  building: Building2,
  users: Users,
  clock: Clock,
  zap: Zap,
  repeat: Repeat,
  calendar: CalendarCheck,
  shield: ShieldCheck,
  lock: Lock,
  database: Database,
  phone: PhoneCall,
  rocket: Rocket,
  gauge: Gauge,
  trending: TrendingUp,
  file: FileText,
  hammer: Hammer,
  star: Star,
  quote: Quote,
  check: Check,
  wrench: Wrench,
  message: MessageSquare,
  search: Search,
  mail: Mail,
  chart: BarChart3,
  settings: Settings,
  sparkles: Sparkles,
  calculator: Calculator,
  scale: Scale,
  receipt: Receipt,
  kanban: FolderKanban,
  bot: Bot,
  workflow: Workflow,
  pin: MapPin,
  phoneSimple: Phone,
  globe: Globe,
  camera: Camera,
  megaphone: Megaphone,
  clipboard: ClipboardList,
  spreadsheet: FileSpreadsheet,
  banknote: Banknote,
  shieldSimple: Shield,
  mobile: Smartphone,
  send: Send,
  bell: Bell,
  lineChart: LineChart,
  layers: Layers,
  plug: Plug,
  table: Table2,
  fileCheck: FileCheck,
  folder: Folder,
  inbox: Inbox,
  timer: Timer,
} satisfies Record<string, LucideIcon>

export type IconKey = keyof typeof ICONS

export function getIcon(key: IconKey): LucideIcon {
  return ICONS[key] ?? Check
}
